channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - dataclasses==0.6
  - numpy==2.1.3
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
