name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous integration"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Python and Hugging Face CLI
      run: | 
        pip install -U "huggingface_hub[cli]"
        pip install dvc[s3]

    - name: Set up Git LFS
      run: |
            sudo apt-get update
            sudo apt-get install git-lfs
            git lfs install


    - name: Deploy to Hugging Face Space
      env:
        HF: ${{ secrets.HF }}
        NAME: ${{ secrets.USER_NAME }}
        EMAIL: ${{ secrets.USER_EMAIL }}
        DAGSHUB_KEY: ${{ secrets.DAGSHUB_KEY }}
        DAGSHUB_SECRET: ${{ secrets.DAGSHUB_SECRET }}
      run: make deploy HF=${HF} USER_NAME=$NAME USER_EMAIL=$EMAIL