name: Continous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show current working directory
      run: pwd && ls -la

    - name: Lihat file Makefile
      run: cat Makefile

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
      
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install skops gradio

    - name: Run training pipeline
      run: python src/train_pipeline.py

    - name: Save evaluation result
      run: |
        ls results/
        cat results/csv/evaluation_metrics.csv

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
    
    - name: Update branch
      if: github.ref == 'refs/heads/main'
      env:
        NAME: ${{ secrets.USER_NAME }}
        EMAIL: ${{ secrets.USER_EMAIL }}
        TOKEN: ${{ secrets.PAT_TOKEN }}
        REPO: ${{ github.repository }}
      run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL TOKEN=$TOKEN REPO=$REPO




        
